 CREATE TABLE TAB_PADRAO
 (ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 DESCRITOR VARCHAR(10) NOT NULL,
    Endereco varchar (100) NULL, 
    Cidade varchar (50) DEFAULT ON NULL 'Rio de Janeiro',
    Data_Criacao Date default ON NULL SYSDATE,
    Primary Key (ID));
    
INSERT INTO TAB_PADRAO (Descritor, endereco, cidade, Data_criacao)
    Values ('Cliente X' , 'Rua Projetada A', 'Sao Paulo', To_Date('2019-01-01', 'YYYY-MM-DD'));
    
Select * from tab_padrao;

insert into tab_padrao(descritor)
    values ('Cliente Y');
    
