CREATE TABLE TAB_INDENTITY
    (ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
        DESCRITOR VARCHAR(20),
        PRIMARY KEY (ID));
        
SELECT * FROM TAB_INDENTITY;

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 1');

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 2');

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 3');

delete from tab_indentity where id = 2;

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 4');

delete from tab_indentity where id = 4;

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 5');

INSERT INTO TAB_INDENTITY (ID, DESCRITOR) values (7, 'Cliente 7');

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 6');

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 7A');

DELETE FROM TAB_INDENTITY WHERE ID = 7;

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente 9');

INSERT INTO TAB_INDENTITY (descritor) values ('Cliente X');

INSERT INTO TAB_INDENTITY (ID,DESCRITOR) VALUES (NULL, 'CLIENTE Y');