
SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM VENDEDORES;

UPDATE Tabela_de_vendedores 
    SET DE_FERIAS = 0
    WHERE MATRICULA IN ('00236','00237');
    
UPDATE Tabela_de_vendedores 
    SET DE_FERIAS = 1
    WHERE MATRICULA IN ('00235','00238');
    
SELECT A.MATRICULA, B.MATRICULA, A.NOME, A.FERIAS, B.DE_FERIAS
    FROM VENDEDORES A 
    INNER JOIN TABELA_DE_VENDEDORES B
    ON A.MATRICULA = SUBSTR(B.MATRICULA,3,3);
    
UPDATE VENDEDORES A 
    INNER JOIN TABELA_DE_VENDEDORES B
    ON A.MATRICULA = SUBSTR(B.MATRICULA,3,3)
    SET A.FERIAS = B.DE_FERIAS;
    
-- EXISTS

SELECT A.MATRICULA, A.NOME, A.FERIAS
    FROM VENDEDORES A WHERE EXISTS(SELECT 1 FROM TABELA_DE_VENDEDORES B
    WHERE A.MATRICULA = SUBSTR(B.MATRICULA,3,3));
    
INSERT INTO TABELA_DE_VENDEDORES (Matricula, nome, percentual_comissao, data_admissao, de_ferias, bairro)
    values ('00239', 'Jose', 0.12, TO_date('2018-01-01', 'YYYY-MM-DD'), '1', 'Tijuca');
    
SELECT * FROM TABELA_DE_VENDEDORES;

UPDATE Vendedores A SET A.Ferias = 
    (SELECT B.De_ferias FROM TABELA_DE_VENDEDORES B
    WHERE A.MATRICULA = SUBSTR(B.MATRICULA,3,3))
    WHERE EXISTS(SELECT 1 FROM TABELA_DE_VENDEDORES B
    WHERE A.MATRICULA = SUBSTR(B.MATRICULA,3,3));