
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO AS codigo, NOME_DO_PRODUTO as descritor,
SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA as preco_lista
FROM TABELA_DE_PRODUTOS;

Insert into produtos
SELECT CODIGO_DO_PRODUTO AS codigo, NOME_DO_PRODUTO as descritor,
SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA as preco_lista
FROM TABELA_DE_PRODUTOS;

ALTER TABLE
    Produtos 
        MODIFY (Embalagem varchar(50)); 
        
SELECT * FROM PRODUTOS;

Insert into produtos
SELECT CODIGO_DO_PRODUTO AS codigo, NOME_DO_PRODUTO as descritor,
SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA as preco_lista
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO <> 1040107;

SELECT * FROM PRODUTOS;