SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE,SEXO, LIMITE_CREDITO,
VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT CPF, NOME, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT IDADE, CPF, NOME, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT CPF AS CPF_DO_CLIENTE, NOME AS NOME_DO_CLIENTE, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1037797';

SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Cítricos';

SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES WHERE IDADE = 22;

SELECT * FROM TB_CLIENTES WHERE IDADE > 22;

SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;

SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;

SELECT * FROM TB_CLIENTES WHERE NOME >= 'Fernando Cavalcante';

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.008

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA <> 16.008

