CREATE TABLE TABELA_DE_VENDEDORES
(MATRICULA VARCHAR(5),
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT);

ALTER TABLE TABELA_DE_VENDEDORES ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY( MATRICULA)

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'José Geraldo da Fonseca', 0.10);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00235', 'Márcio Almeida Silva', 0.08);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236', 'Cláudio Morais', 0.08);

SELECT * FROM TABELA_DE_VENDEDORES

UPDATE TABELA_DE_VENDEDORES SET 
PERCENTUAL_COMISSAO = 11
WHERE 
MATRICULA = '00236';

UPDATE TABELA_DE_VENDEDORES SET
NOME = 'José Geraldo da Fonseca Junior'
WHERE
MATRICULA = '00233'

DELETE FROM TABELA_DE_VENDEDORES
WHERE MATRICULA = '00233';

ALTER TABLE TABELA_DE_VENDEDORES ADD DATA_ADMISSAO DATE;
ALTER TABLE TABELA_DE_VENDEDORES ADD DE_FERIAS NVARCHAR2(3);

UPDATE TABELA_DE_VENDEDORES SET
DATA_ADMISSAO = TO_DATE('15/08/2014', 'DD/MM/YYYY')
WHERE MATRICULA = '00235';

UPDATE TABELA_DE_VENDEDORES SET
DE_FERIAS = 'Não'
WHERE MATRICULA = '00235'

UPDATE TABELA_DE_VENDEDORES SET
DATA_ADMISSAO = TO_DATE('17/09/2013', 'DD/MM/YYYY'), DE_FERIAS = 'Sim'
WHERE MATRICULA = '00236';

UPDATE TABELA_DE_VENDEDORES SET
PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins',0.11,TO_DATE('18/03/2017','DD/MM/YYYY'),'Sim');

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00238','Péricles Alves',0.11, TO_DATE('21/08/2016','DD/MM/YYYY'),'Não');

SELECT * FROM TABELA_DE_VENDEDORES

SELECT MATRICULA, NOME FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME ='Cláudio Morais';

SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM TABELA_DE_VENDEDORES WHERE DATA_ADMISSAO >= TO_DATE('01/01/2016', 'DD/MM/YYYY');

SELECT * FROM TABELA_DE_VENDEDORES WHERE DE_FERIAS = 'Sim' and DATA_ADMISSAO < TO_DATE('01/01/2016', 'DD/MM/YYYY');